name: Apply

on:
  push:
    branches:
      - master # we want this to be executed on the default branch only
  workflow_dispatch:

jobs:
  prepare:
    if: github.event.repository.is_template == false
    permissions:
      contents: read
      issues: read
      pull-requests: read
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.workspaces.outputs.this }}
      sha: ${{ steps.sha.outputs.result }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Discover workspaces
        id: workspaces
        run: echo "this=$(ls github | jq --raw-input '[.[0:-4]]' | jq -sc add)" >> $GITHUB_OUTPUT
      - name: Find sha for plan
        id: sha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUERY: repository:${{ github.repository }} ${{ github.sha }}
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            if (process.env.GITHUB_EVENT_NAME === 'push') {
              const { data: search } = await github.rest.search.issuesAndPullRequests({
                q: process.env.QUERY,
                per_page: 1
              });
              if (search.total_count !== 0) {
                const { data: pulls } = await github.rest.pulls.listCommits({
                  owner: process.env.GITHUB_REPOSITORY_OWNER,
                  repo: process.env.GITHUB_REPOSITORY.slice(process.env.GITHUB_REPOSITORY_OWNER.length + 1),
                  pull_number: search.items[0].number,
                  per_page: 100
                });
                return pulls.at(-1).sha;
              } else {
                return '';
              }
            } else {
              return process.env.GITHUB_SHA;
            }
  apply:
    needs: [prepare]
    if: needs.prepare.outputs.sha != '' && needs.prepare.outputs.workspaces != ''
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.prepare.outputs.workspaces) }}
    name: Apply
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: 1
      TF_INPUT: 0
      TF_WORKSPACE: ${{ matrix.workspace }}
      AWS_ACCESS_KEY_ID: ${{ secrets.RW_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.RW_AWS_SECRET_ACCESS_KEY }}
      GITHUB_APP_ID: ${{ secrets.RW_GITHUB_APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets[format('RW_GITHUB_APP_INSTALLATION_ID_{0}', matrix.workspace)] || secrets.RW_GITHUB_APP_INSTALLATION_ID }}
      GITHUB_APP_PEM_FILE: ${{ secrets.RW_GITHUB_APP_PEM_FILE }}
      TF_VAR_write_delay_ms: 300
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: 1.3.7
      - name: Initialize terraform
        run: terraform init
      - name: Terraform Plan Download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ needs.prepare.outputs.sha }}
        run: gh run download -n "${TF_WORKSPACE}_${SHA}.tfplan" --repo "${GITHUB_REPOSITORY}"
      - name: Terraform Apply
        run: terraform apply -lock-timeout=0s -no-color "${TF_WORKSPACE}.tfplan"
